{
 "title": "Home Monitoring",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Live Current Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current{label=\"phase1\"}",
     "legendFormat": "Phase 1"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "current{label=\"phase1\"} * 240.0",
     "legendFormat": "Phase 1"
    }
   ]
  },
  {
   "title": "Live Power Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current{label=\"phase1\"} * 240",
     "legendFormat": "Phase 1"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum_over_time(current{label=\"phase1\"}[$__interval]) * 240.0 / 1200.0"
    }
   ]
  },
  {
   "title": "Power Usage Today",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time(current{label=\"phase1\"}[$__interval]) * 240.0 / 1200.0"
    }
   ]
  }
 ]
}